<?php

declare(strict_types=1);

namespace App\Notifications;

use Illuminate\Auth\Notifications\VerifyEmail as BaseVerifyEmail;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

/**
 * VerifyEmailNotification.
 *
 * Enterprise-grade email verification notification. Extends Laravel's default
 * VerifyEmail but renders a branded, tenant-aware message and supports queued
 * delivery. The signed verification URL is generated by the framework and is
 * valid for the duration defined in config/auth.php (`verification.expire`).
 */
class VerifyEmailNotification extends BaseVerifyEmail implements ShouldQueue
{
    use Queueable;

    /**
     * Build the mail representation of the notification.
     */
    public function toMail($notifiable): MailMessage
    {
        $verificationUrl = $this->verificationUrl($notifiable);

        return (new MailMessage)
            ->subject('Verify your '.config('app.name').' account')
            ->greeting('Welcome to '.config('app.name').'!')
            ->line('Please click the button below to verify your email address.')
            ->action('Verify Email Address', $verificationUrl)
            ->line('If you did not create an account, no further action is required.')
            ->line('This verification link will expire in '.config('auth.verification.expire', 60).' minutes.')
            ->salutation('Regards, the '.config('app.name').' Security Team');
    }
}
