<?php

declare(strict_types=1);

namespace App\Services\AI\Providers;

use App\Services\AI\AssistantService;

/**
 * MockProvider.
 *
 * An offline, key-free LLM provider used for demonstrations, testing and as a
 * graceful fallback when no external provider key is configured. It does not
 * call any network service; instead it reformats the read-only data context
 * that the {@see AssistantService} already retrieved through
 * the RAG tools into a human-readable answer. This guarantees the AI Academic
 * Assistant works end-to-end (intent -> auth -> retrieve -> generate -> audit)
 * without incurring API cost.
 */
class MockProvider extends AbstractLLMProvider
{
    protected function configKey(): string
    {
        return 'ai.mock';
    }

    public function getName(): string
    {
        return 'Mock (Offline)';
    }

    public function complete(string $prompt, array $options = []): string
    {
        return $this->chat([['role' => 'user', 'content' => $prompt]], $options)['content'];
    }

    public function chat(array $messages, array $options = []): array
    {
        $userMessage = '';
        foreach ($messages as $message) {
            if (($message['role'] ?? '') === 'user') {
                $userMessage = $message['content'] ?? '';
            }
        }

        $data = [];
        if (preg_match('/DATA:\s*(\{.*\})\s*QUESTION:/s', $userMessage, $m)) {
            $decoded = json_decode($m[1], true);
            if (is_array($decoded)) {
                $data = $decoded;
            }
        }

        $question = '';
        if (preg_match('/QUESTION:\s*(.+)$/s', $userMessage, $m)) {
            $question = trim($m[1]);
        }

        $answer = $this->formatAnswer($question, $data);

        return [
            'content' => $answer,
            'tokens' => (int) ceil(strlen($answer) / 4),
        ];
    }

    /**
     * Turn the retrieved data context into a concise, readable answer.
     *
     * @param  array<string, mixed>  $data
     */
    private function formatAnswer(string $question, array $data): string
    {
        if (empty($data)) {
            return 'I could not find any records relevant to your question. '
                .'Please note the assistant is read-only and can only report on '
                .'data your role is permitted to access within your institution.';
        }

        $lines = ['Here is what I found based on the records I am authorised to read:'];

        foreach ($data as $key => $value) {
            $label = ucfirst(str_replace('_', ' ', (string) $key));

            if (is_array($value)) {
                if (empty($value)) {
                    $lines[] = "- {$label}: none";

                    continue;
                }

                if (array_is_list($value)) {
                    $sample = array_slice($value, 0, 8);
                    $count = count($value);
                    $rendered = implode(', ', array_map([$this, 'stringify'], $sample));
                    $more = $count > 8 ? ' (and '.($count - 8).' more)' : '';
                    $lines[] = "- {$label} ({$count}): ".$rendered.$more;
                } else {
                    $parts = [];
                    foreach ($value as $k => $v) {
                        $parts[] = ucfirst(str_replace('_', ' ', (string) $k)).': '.$this->stringify($v);
                    }
                    $lines[] = "- {$label}: ".implode('; ', $parts);
                }
            } else {
                $lines[] = "- {$label}: ".$this->stringify($value);
            }
        }

        $lines[] = '';
        $lines[] = 'Note: this answer was generated by the offline mock provider. '
            .'Configure a real LLM (OpenAI/Claude/Gemini/Local) in your .env to obtain '
            .'natural-language explanations.';

        return implode("\n", $lines);
    }

    /**
     * Render a scalar/array value as a short string for the answer.
     */
    private function stringify(mixed $value): string
    {
        if (is_array($value)) {
            return implode(', ', array_map([$this, 'stringify'], $value));
        }

        if (is_bool($value)) {
            return $value ? 'yes' : 'no';
        }

        return (string) $value;
    }
}
