name: PHPStan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Verify PHPStan
        run: ls -la vendor/bin

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G
